- name: Pull koadic
  become: yes
  docker_image:
    name: vickimgore/koadic
    repository: vickimgore/koadic
    source: pull

- name: Copy docker-compose.yml 
  copy:
    src: docker-compose.yml
    dest: /opt/docker

- name: Spiderfoot up
  command: docker-compose up -d
  become: yes
  args:
    chdir: "{{ workdir }}"