---
- name: Include sshd_config vars
  include_vars:
    file: main.yml

- name: Copy template
  become: yes
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config }}"
    owner:  root
    group:  root
    mode: 0600

#- name: Restart sshd
#  become: yes
#  systemd:
#    state: restarted
#    name: sshd
