- name: Add docker reposity
  become: yes
  yum_repository:
    name: docker
    description: docker repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install docker packages
  become: yes
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Download and Set execution permission
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64
    dest: /bin/docker-compose
    mode: '755'

- name: Add docker-compose
  become: yes
  shell: |
    systemctl enable --now docker
    gpasswd -a {{ username }} docker
    exit 0
